FROM armhf/maven:jdk-8

WORKDIR /proj

# cache dependencies
COPY pom.xml /proj/pom.xml
RUN mvn dependency:resolve
RUN mvn verify

COPY src /proj/src
RUN mvn package

CMD ["java", "-jar", "target/worker-jar-with-dependencies.jar"]
