apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: result
  namespace: default
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/min-scale: "1"
    spec:
      containers:
      - image: ghcr.io/salaboy/result-go
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
        env:
        - name: DAPR_HTTP_ENDPOINT
          value: http://result-dapr.default.svc.cluster.local:3500
        - name: DAPR_GRPC_ENDPOINT
          value: result-dapr.default.svc.cluster.local
