apiVersion: v1
kind: Service
metadata:
  annotations: 
    metallb.universe.tf/ip-allocated-from-pool: first-pool
  labels:
    app: result
  name: result
spec:
  type: LoadBalancer
  ports:
  - name: "result-service"
    port: 5001
    targetPort: 80
    nodePort: 31001
  selector:
    app: result
