---
apiVersion: v1
kind: Service
metadata:
  annotations: 
    metallb.universe.tf/ip-allocated-from-pool: first-pool
  labels:
    app: vote
  name: vote
spec:
  type: LoadBalancer
  ports:
  - name: "vote-service"
    port: 5000
    targetPort: 80
    nodePort: 31000
  selector:
    app: vote
  
